footnotes = {
    "footnote1": "Or, one would hope so. \“Adriana’s Seven Steps to Business Success\” alone cost one hundred and fifty dollars. It was her lowest value course.",

    "footnote2": "This is by far the most inane term for a non-mage I’ve ever heard. I won’t pretend like the selection of terms available doesn’t leave much to be desired, but if I had qualms with the most commonly used mundane, then this derivative is certainly not an improvement. Fortunately I’ve yet to hear it employed by anyone but you.",

    "footnote3" : "Mildred R. DuPont, <em>An Atlas of North American Ley Lines</em>. Manuscript. 1954, pg. 62, Personal Library of Oleander Etterdam." +
    "<br>&emsp;Though the book was published decades ago, I would still expect its information to be accurate. There’s ample evidence that ley lines move, but at a speed comparable to tectonic plates. The atlas would presumably be usable for a few millennia.",

    "footnote4" : "Modern spellcasters usually attempt emulating academic rigor, with varying success. At the very least, they can be relied upon to share their own experience casting their spells, or a cursory explanation of how their spells work. The mages of bygone eras, however, often could not be assed to provide more than instructions. Or perhaps -- if they were feeling generous -- they might impart a vague understanding of what their spells did. Which is why most wizards of this century accurately regard old magic as not worth their while. That is, unless you are, unfortunately, <em>me</em>.",

    "footnote5" : "I first encountered the spell in the New York Library special archives, among the personal notes of a long-dead mage by the name of Theodor von Schulz. Schulz was not the spell’s original author. According to him, it was discovered amidst a pile of moldering parchment in the shelves of a monastery. He was kind enough to transcribe the Old English and provide his own, rather competent, translation of the incantation. However he didn’t have much to say about the spell otherwise, being unable to cast it himself. I wanted to see the original writings, but predictably, my various inquiries to track down the rest of his collection led me absolutely nowhere, except to a rather lengthy phone call with an overseas archivist. While said archivist was not able to find my requested materials, he was able to expand my German vocabulary around the subject of dust, the trials of having a dust allergy, and ways to curse the existence of dust, having insisted upon my being on the line while he searched the archives.",

    "footnote6" : "<em>You.</em>",

    "footnote7" : "With the exception of the time I accidentally set my sleeve on fire poking around the ley line in Nevada. But spontaneous combustion is almost expected when dealing with anything infernal, and I should have known better to be trying it that close to Las Vegas anyway, and I could tell the moment I reached that line that it was very inclined to set me on fire, and finding out that sort of thing is the whole point of the spell. Besides, the burns were only first-degree, so it hardly compared to the current <em>situation</em>.",

    "footnote8" : "This is what you called it, after you wouldn’t stop harassing me to explain what I was doing the first time you saw me perform the spell. I begrudgingly admit the name is not entirely inaccurate.",

    "footnote9" : "While not among the most dangerous, ghouls are generally agreed to be one of the more distasteful monsters one may have the misfortune of meeting. The honor is owed to their hunting methods; they are capable of causing immediate tissue death upon physical contact with their victims. The ability extends, to a lesser degree, to its bodily fluids and deceased remains. It makes cleanup a rather annoying and arduous task. If there are any fortunate qualities one might ascribe to ghouls, they are that ghouls are blessedly uncommon. And, unlike most natural necrosis, necrosis from ghoul magic is not caused by bacterial infection. There is therefore no immediate concern for blood poisoning, although the afflicted area must still be removed as soon as possible. Dead tissue quickly becomes a prolific breeding ground for bacteria either way. But as long as the site of necrosis is dealt with promptly, the resulting wound may be treated as any normal injury.",

    "footnote10" : "According to <em>An Encyclopedia of Apotropaic Magic</em>, wards fall into one of two classes: active and passive. (The book is largely the author’s attempt to organize the broad field of protection magic into neat categories. I found it often harmfully reductive, but this particular classification for wards I consider useful). Active wards require, as the name implies, an active source of mana. Said mana can be supplied upon the creation of the ward, stored internally like electricity inside a battery. Or, the ward can be made to draw mana from the user when needed." +
    "<br>&emsp;I find the former far easier to make, although in this particular instance I wish I’d gone through the trouble of making the latter. The last of my wards burned away right as the thing finally died, or died as much as ghouls can die. I was very lucky it had let go of me by then. As it were, only a small amount of its blood got on me thus unprotected. The necrosis didn’t penetrate past my skin. In the end the injury was honestly quite trivial once treated, but I’m always displeased any time I end up having to perform surgery on myself."
}
